### ISSUE TITLE
User can see all PAWS visualized on a map

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-waterfront-access#1]

**Comment by hannahkates** [comment]
These will come from a combination of sources
- Some PAWS have exact footprints available. Some will show the entire tax lots.
- Private vs. city vs. other

**Comment by hannahkates** [comment]
Questions:
- [ ] What's the best field to use to distinguish between the PAWS types?
- [ ] Should additional polygons be used to show actual footprint, where available?

**Comment by hannahkates** [comment]
- [ ] Create LayerGroup and Sources in labs-layers-api
- [ ] Add these to the map using labs-layers
