### ISSUE TITLE
Profile displays basic information about area

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-waterfront-access#17]
- [ ] Name
- [ ] Address
- [ ] Property Owner
- [ ] Chair Certification (when space was approved)
- [ ] Dept of Parks & Rec Declaration ID (link to ACRIS)
- [ ] CPC report number (w/ link)
- [ ] WPA(?) Total Access Area in sq ft
- [ ] Hours Open
- [ ] Adjacent Waterway (e.g. "East River")
- [ ] Boat launch (geo-referenced points)
- [ ] Shore Public Walkway Linear ft
- [ ] Summary of Open Spaces (text description) 
- [ ] Construction status
- [ ] Upland connections (count of access points)
- [ ] Flag sites pre-1992 that were created before the waterfront zoning policy.

**Comment by hannahkates** [comment]
Commit 44de65f added all the profile content to the model and the template. Now UI and design work is needed.
