### ISSUE TITLE
Feature WPAAs from new December data

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-waterfront-access#173]
The waterfront team wants to highlight new sites on the About tab: 
![image](https://user-images.githubusercontent.com/13967925/72179556-24560080-33b3-11ea-950a-f58927ddba97.png)

New ones to highlight instead of the existing ones:
- Richmond Terrace Park, Staten Island (Photo credit: Malcolm Pinckney/NYC Parks)
- Skyview Parc, Queens
- 155 West Street, Brooklyn
- Shirley Chisolm State Park, Brooklyn

Photos:
[RE__Waterfront_Access_Map_Update_.zip](https://github.com/NYCPlanning/labs-waterfront-access/files/4047434/RE__Waterfront_Access_Map_Update_.zip)
ShirleyChisolm ![ShirleyChisolm1](https://user-images.githubusercontent.com/13967925/72841666-d1a6ff00-3c64-11ea-892b-f2b53aafa1ad.jpg)

**Comment by trbmcginnis** [comment]
So these are the links I'm associating with each of these new photos:

Richmond Terrace: https://www.nycgovparks.org/parks/richmond-terrace-wetlands
Shirley Chisholm: https://parks.ny.gov/parks/200/details.aspx
Skyview Parc: link to the profile with ID 4070005
155 West Street: link to the profile with ID 3010008
