### ISSUE TITLE
User can view a profile for a particular PAWS

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-waterfront-access#2]

**Comment by andycochran** [comment]
Questions: 
- Should all waterfront access areas have profiles? 
- Should the routes be specific to the type of area? e.g.… 
  - /paws/:id
  - /parks/:id
  - /[type]/:id

**Comment by hannahkates** [comment]
The routes are now set up as profiles/:id.

**Comment by hannahkates** [comment]
PR #42 added click events that open the profiles/show page for each PAWS site. Commit 44de65ff334f2c817dad0db3b76fd2afc7b68a4d added all the profile content to the model and the template. Now UI and design work is needed.
