### ISSUE TITLE
User can filter the mapped access areas by amenity

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-waterfront-access#24]
- lighting 
- unspecified plantings
- entry gates
- designated bike paths
- bike racks
- other circulation paths
- ground floor retail
- piers
- ferry/water taxi service
- boat launch
- public access easement
- guardrails
- public art
- interpretive displays
- trash receptacles
- handicapped accessible
- emergency access

**Comment by allthesignals** [comment]
<img width="520" alt="screen shot 2018-10-16 at 3 33 49 pm" src="https://user-images.githubusercontent.com/5004319/47042306-ec80ee80-d158-11e8-88dd-16b650e798c9.png">

**Comment by allthesignals** [comment]
Only filter the privately owned spaces

**Comment by allthesignals** [comment]
Here's a map of checklist item to column name:

data_type | column_name | Checklist
-- | -- | --
boolean | visual_corridors |  
boolean | seating |  
boolean | lighting | lighting
boolean | trees |  
boolean | other_planting | unspecified plantings
boolean | entry_gates | entry gates
boolean | designated_bike_path | designated bike paths
boolean | bike_racks | bike racks
boolean | other_circulation_paths | other circulation paths
boolean | ground_floor_retail | ground floor retail
boolean | piers | piers
boolean | ferry_watertaxi__service | ferry/water taxi service
boolean | boat_launch | boat launch
boolean | public_access_easement | public access easement
boolean | guardrail | guardrails
boolean | public_art | public art
boolean | interpretive_displays | interpretive displays
boolean | trash_receptacles | trash receptacles
boolean | handicapped_accessible | handicapped accessible
boolean | emergency_access | emergency access
boolean | publicly_accessible_walkway |  
boolean | shore_public_walkway |  
boolean | upland_connections |  
boolean | spaa |  
boolean | ground_cover |  
boolean | signage |  

The master table is non-spatial, so we will linked through join key (which is `paws_id`).

**Comment by allthesignals** [comment]
We need a way to mutate all three layers at once. We can make our component accept a collection of models. We could also create a function that does this in the `layerGroup` model
