### ISSUE TITLE
Sort out data pipeline

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-waterfront-access#26]
Data is currently in an Access database. Waterfront wants a new/better way to manage the data (note: is engaged in a process of doing so). We should figure out the best way to store and maintain the data and advise on this.

**Comment by hannahkates** [comment]
WOS has provided two shapefiles. One containing only privately owned PAWS (minus DOS spaces), the second containing all official parks and publicly owned spaces. This will simplify the logic of figuring out which sites get profiles vs which have external URLs. The categories on the legend will also follow this binary distinction, making it easier for users to see which are private vs. not.
