### ISSUE TITLE
Filter by construction status

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-waterfront-access#27]
Currently, the statuses are: 

Constructed (access limited) / Phase 1 Constructed
Not Started
Constructed
Natural State
In Progress
Constructed (access limited) / Phase 1 & Phase 2 Constructed, Phase 3 in Progress
Constructed (full access)
Constructed (access restricted)
In Progress (Phase 1)

**Comment by allthesignals** [comment]
Are there multiple statuses for this?

**Comment by hannahkates** [comment]
No longer needed because this will be styled instead
