### ISSUE TITLE
Profile displays large photo(s)

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-waterfront-access#3]
Each access area shows a prominent photo (or set of photos). Some will be high quality, some not. Areas that are under construction will not have photos, so we'll need to figure out how to handle those.

**Comment by hannahkates** [comment]
Photos are in this drive folder. The preferred spotlight photo is #1 fir each. https://drive.google.com/drive/folders/1Ccq2eXEUyLehB8RhYWMvvqepzaHv0vhE?usp=sharing
