### ISSUE TITLE
User can see footprints for each WPAA site

### ISSUE THREAD

**Issue by trbmcginnis** [NYCPlanning/labs-waterfront-access#31]
-not as relevant on citywide scale, but when zoomed in have it as an overlay

-overlaps with access points (points sit on border)--nice visual connection from streets to access points

**Comment by hannahkates** [comment]
I'm solving this by inserting the new footprints that @CWASSIF created into the existing table of footprints.

**Comment by CWASSIF** [comment]
Sounds good @hannahkates but we are currently trying to get the footprints confirmed by the borough offices, so there will likely be an updated version of the shapefile soon.
