### ISSUE TITLE
Select amenities for checkbox list

### ISSUE THREAD

**Issue by trbmcginnis** [NYCPlanning/labs-waterfront-access#33]
Can remove some amenities from the list (e.g. lighting, trash, guard rails, entry gates). These checkboxes are meant to filter out areas that have popular amenities (e.g. bike routes).

**Comment by hannahkates** [comment]
Remaining tasks based on new amenities list
- [x] Split amenity arrays into boolean columns and update tables on Carto
- [ ] Update filters
- [ ] Update profiles

**Comment by hannahkates** [comment]
SQL used to split arrays into new columns:
`alter table pawsmastertable
add column feature_Promenade_Esplanade boolean;

update pawsmastertable
set feature_Promenade_Esplanade = true
from wpaas_grid_view AS revised
where revised.paws_id = pawsmastertable.paws_id AND revised.site_features LIKE '%Promenade/Esplanade%';

alter table pawsmastertable
add column feature_Seating_Lawn boolean;

update pawsmastertable
set feature_Seating_Lawn = true
from wpaas_grid_view AS revised
where revised.paws_id = pawsmastertable.paws_id AND revised.site_features LIKE '%Seating Lawn%';

alter table pawsmastertable
add column feature_Pier boolean;

update pawsmastertable
set feature_Pier = true
from wpaas_grid_view AS revised
where revised.paws_id = pawsmastertable.paws_id AND revised.site_features LIKE '%Pier%';

alter table pawsmastertable
add column feature_Wetland_Natural_Edge boolean;

update pawsmastertable
set feature_Wetland_Natural_Edge = true
from wpaas_grid_view AS revised
where revised.paws_id = pawsmastertable.paws_id AND revised.site_features LIKE '%Wetland/Natural Edge%';

alter table pawsmastertable
add column feature_Dog_run boolean;

update pawsmastertable
set feature_Dog_run = true
from wpaas_grid_view AS revised
where revised.paws_id = pawsmastertable.paws_id AND revised.site_features LIKE '%Dog run%';

alter table pawsmastertable
add column feature_Educational_or_Interpretive boolean;

update pawsmastertable
set feature_Educational_or_Interpretive = true
from wpaas_grid_view AS revised
where revised.paws_id = pawsmastertable.paws_id AND revised.site_features LIKE '%Educational or Interpretive features%';

alter table pawsmastertable
add column feature_Public_restroom boolean;

update pawsmastertable
set feature_Public_restroom = true
from wpaas_grid_view AS revised
where revised.paws_id = pawsmastertable.paws_id AND revised.site_features LIKE '%Public restroom%';

alter table pawsmastertable
add column feature_Shade_structure boolean;

update pawsmastertable
set feature_Shade_structure = true
from wpaas_grid_view AS revised
where revised.paws_id = pawsmastertable.paws_id AND revised.site_features LIKE '%Shade structure%';

alter table pawsmastertable
add column feature_Outdoor_art boolean;

update pawsmastertable
set feature_Outdoor_art = true
from wpaas_grid_view AS revised
where revised.paws_id = pawsmastertable.paws_id AND revised.site_features LIKE '%Outdoor art%';

alter table pawsmastertable
add column feature_Food_or_Beverage_Concessions boolean;

update pawsmastertable
set feature_Food_or_Beverage_Concessions = true
from wpaas_grid_view AS revised
where revised.paws_id = pawsmastertable.paws_id AND revised.site_features LIKE '%Food or Beverage Concessions%';

alter table pawsmastertable
add column feature_Group_Seating boolean;

update pawsmastertable
set feature_Group_Seating = true
from wpaas_grid_view AS revised
where revised.paws_id = pawsmastertable.paws_id AND revised.site_features LIKE '%Group Seating%';

alter table pawsmastertable
add column activity_Volleyball_Court boolean;

update pawsmastertable
set activity_Volleyball_Court = true
from wpaas_grid_view as revised
where revised.paws_id = pawsmastertable.paws_id AND revised.active_amenities LIKE '%Volleyball Court%';

alter table pawsmastertable
add column activity_Basketball_Court boolean;

update pawsmastertable
set activity_Basketball_Court = true
from wpaas_grid_view as revised
where revised.paws_id = pawsmastertable.paws_id AND revised.active_amenities LIKE '%Basketball Court%';

alter table pawsmastertable
add column activity_Fishing boolean;

update pawsmastertable
set activity_Fishing = true
from wpaas_grid_view as revised
where revised.paws_id = pawsmastertable.paws_id AND revised.active_amenities LIKE '%Fishing%';

alter table pawsmastertable
add column activity_Boating_Access boolean;

update pawsmastertable
set activity_Boating_Access = true
from wpaas_grid_view as revised
where revised.paws_id = pawsmastertable.paws_id AND revised.active_amenities LIKE '%Boating/In-water Access%';

alter table pawsmastertable
add column activity_Tot_Playground boolean;

update pawsmastertable
set activity_Tot_Playground = true
from wpaas_grid_view as revised
where revised.paws_id = pawsmastertable.paws_id AND revised.active_amenities LIKE '%Tot Playground%';

alter table pawsmastertable
add column activity_Splash_Feature boolean;

update pawsmastertable
set activity_Splash_Feature = true
from wpaas_grid_view as revised
where revised.paws_id = pawsmastertable.paws_id AND revised.active_amenities LIKE '%Splash Feature%';

alter table pawsmastertable
add column activity_Other_Recreational_facilities boolean;

update pawsmastertable
set activity_Other_Recreational_facilities = true
from wpaas_grid_view as revised
where revised.paws_id = pawsmastertable.paws_id AND revised.active_amenities LIKE '%Other Recreational facilities (Bocce, Skate Park, etc)%';

alter table pawsmastertable
add column activity_Swimming boolean;

update pawsmastertable
set activity_Swimming = true
from wpaas_grid_view as revised
where revised.paws_id = pawsmastertable.paws_id AND revised.active_amenities LIKE '%Swimming%';
`
