### ISSUE TITLE
Finish "About" content

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-waterfront-access#55]
- [x] Compute a total count of publicly accessible waterfront spaces
- [x] Compute a count on public property
- [x] Compute a count on private property
- [x] Use these computed properties to fill in the red blanks in the last paragraph on the About page
- [x] Nix the `<span class="red">` tags, use `<strong>` tags on the numbers instead
- [ ] Also make sure to emphasize that the City incentivizes the creation of these spaces through zoning policies aimed at created more waterfront access for the public.

**Comment by chriswhong** [comment]
WITH 
publiclyowned AS (
	SELECT 
  		count(*) 
  	FROM planninglabs.publiclyownedwaterfront_v201810
),

paws AS (
	SELECT 
  		count(*) 
  	FROM wpaas_v201810
)

SELECT 
	publiclyowned.count AS publiclyowned_count,
	paws.count AS paws_count,
	publiclyowned.count + paws.count AS total_count
FROM publiclyowned, paws

**Comment by hannahkates** [comment]
Also make sure to emphasize that the City incentivizes the creation of these spaces through zoning policies aimed at created more waterfront access for the public.

**Comment by andycochran** [comment]
It looks like this work was lost. I know at one point I saw these computed numbers working on the about page. I'm wondering if there was a squash/rebase/something that happened and lost some history. Because I cannot find evidence of this work being done. 

Has GitHub changed the way that deleted branches works? They're all gone. You used to be able to get them back. But I no longer see that option. 

/cc @allthesignals
