### ISSUE TITLE
Fix CPC Report Link

### ISSUE THREAD

**Issue by trbmcginnis** [NYCPlanning/labs-waterfront-access#60]
Talk to planners about which locations link out to CPC report. This is based on the actions that accompany the site's zoning change. Here is a google sheets that was used to differentiate between actions that do have CPC reports and those that do not on ZAP. The issue is that sometimes it can be a case-by-case basis, so certain actions that usually do not have CPC reports might have them for a specific case. 

https://docs.google.com/spreadsheets/d/1vqltSmsVk14Xhr0CEBgc8FVhtKVGmN7w0Wbi9PeGY2s/edit?usp=sharing

**Comment by hannahkates** [comment]
This required a data fix. URLs are only provided in the data if a report exists, but the export from the access database included #s and NAs that need to be removed.

![image (1).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/593ac159e983f40020992a93/125516c66e82c728ace21e0d46e1999b2487c3e1dea0fd0fe64de29b234324676b5ee17e7284e02eec1022595b0d1afa44585f42fef88b7eafb76f62964e49bc8f3900299f7744eeaa880dbe06b0218e4c8cb1bd8e4dc9ec3421e699c2.png)
