### ISSUE TITLE
Edit geometry of polygons so that users can see what exactly is accessible

### ISSUE THREAD

**Issue by trbmcginnis** [NYCPlanning/labs-waterfront-access#67]
Some polygons cover an entire area (including buildings), where some of the land might be accessible publicly and some is private. This might confuse users if they were to try to visit and walk on the entire site. Talk to planners about the best way to show this. 

e.g. Ikea property has polygon over entire Ikea building and parking lot

**Comment by hannahkates** [comment]
Will be addressed by #113
