### ISSUE TITLE
Park name, hours, construction status in map tooltip

### ISSUE THREAD

**Issue by trbmcginnis** [NYCPlanning/labs-waterfront-access#68]
And also certain amenities? Make this into more of a pop-up like we have in CityMap?

**Comment by chriswhong** [comment]
Hours seems overkill for a tooltip.  Construction Status maybe, but I'd rather we just symbolize the in-construction projects differently. 

I think just showing the name of the park is fine, it's enough to help the user figure out if they want to click for more info.

**Comment by hannahkates** [comment]
I don't think this relevant anymore. Publicly owned parks have a pop up now that provide park info, and users can click on WPAAs to easily get info without losing the ability to continue browsing the map.
